package com.sunbase.CustomerApp.util;

import org.mindrot.jbcrypt.BCrypt;

/**
 * Interface for Bcrypt encryption utility methods.
 * These methods handle password encryption and password matching using BCrypt.
 */
public interface BcryptEncryption {

    /**
     * Encrypts the given plain text password using BCrypt.
     *
     * @param textPassword The plain text password to be encrypted.
     * @return The hashed password generated by BCrypt.
     */
    public static String bcryptEncryption(String textPassword) {
        return BCrypt.hashpw(textPassword, BCrypt.gensalt());
    }

    /**
     * Checks if the provided user password matches the hashed password stored in the database.
     *
     * @param userPassword The plain text password entered by the user.
     * @param dbPassword   The hashed password stored in the database.
     * @return True if the passwords match, false otherwise.
     */
    public static boolean checkPassword(String userPassword, String dbPassword) {
        if (BCrypt.checkpw(userPassword, dbPassword)) {
            System.out.println("Password Matched");
            return true;
        } else {
            return false;
        }
    }
}

